// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	ProductName   string  `json:"productName"`
	OrgCode       string  `json:"orgCode"`
	JanCode       *string `json:"janCode"`
	ProductDetail *string `json:"productDetail"`
	ProductPrice  *int    `json:"productPrice"`
	Rating        *int    `json:"Rating"`
	Review        *int    `json:"Review"`
	ProductImage  *string `json:"productImage"`
}
